### ISSUE TITLE
Divergence between OSX theme name and directory name

### ISSUE THREAD

**Issue by romildo** [darkomarko42/Luna-Icons#1]
The name in `index.theme` is `Luna X`, but the directory name is `Luna icons OSX`.
Similar issue for the light and dark variants.

**Comment by darkomarko42** [comment]
fixed up :)

**Comment by romildo** [comment]
It seems that there is still an inconsistency: the directory name is `Luna icons OSX`, and the theme name in `index.theme` is `Luna OSX`.
